### ISSUE TITLE
Селекторы не работают в Chrome (проверено в v58.0.x)

### ISSUE THREAD

**Issue by gshark** [team411/src2img#16]
При попытке открыть шорткат для выбора языка или темы, шорткат мнгновенно закрывается:(

**Comment by corpix** [comment]
@gshark что такое шорткат? Полагаю что имелся в виду select.

Проверил только что в firefox 53 - всё ок. А в chromium 58 воспроизводится, поправим как руки дойдут :)

**Comment by ololobus** [comment]
@corpix При этом в последнем Сафари 10.1.1 все ок, а в Хроме 58, да, сломано. Интересно, что они там такого в БЭМе могли заюзать, а в последнем Хромиуме сломать? оО

**Comment by corpix** [comment]
Эх, полез собирать все эти бэм прелести, а они более не собираются. Так что у меня предложение... может на реакт перепишем? Там изи вообще :)

**Comment by rndD** [comment]
в целом да, давай. Я щас попробую собрать. Мне просто интересно почему оно может не собираться.

**Comment by rndD** [comment]
Ахаха это мамонт. Его можно собрать только на ноде 0.12. Предлагаю пофиксить а потом переписать на react под пиво или 420.

**Comment by ololobus** [comment]
@rndD  Тут вроде не так много БЭМ-библиотек, нельзя просто все их апнуть до последних не мажорных версий? Про переписать под пиво я за :)

**Comment by rndD** [comment]
В целом скорей всего обновление bem components должно помочь. Но там начинается enb dependency hell.

**Comment by rndD** [comment]
благодаря @zxqfox получилось пофиксить =) но мы не осиляторы деплоя на gh-pages. Статику не видит. @ololobus ты помнишь как там кошерно собрать?

**Comment by ololobus** [comment]
@rndD При сборке все пути к статике указываются как `/_/6wPG2siTHqaye446l0eqi_8dskQ.css` поэтому он ищет их в https://team411.github.io/. А должны быть относительные типа `_/...`, так как адрес https://team411.github.io/src2img

Я вроде все пофиксил, но лого пропало %) Надо еще посмотреть

**Comment by ololobus** [comment]
Кажется, теперь совсем все ок, но навскидку есть пара багов точно =)

**Comment by ololobus** [comment]
1. У селекторов нет скролла, поэтому они выпадают огромной длинной простыней
2. Автодетект языка срабатывает после каждого изменения, даже если язык уже выбран. Все время бросает меня с JS на ActionScript

**Comment by ololobus** [comment]
Это тоже пофиксил

**Comment by rndD** [comment]
кхм у меня src2img.com открывается.

**Comment by corpix** [comment]
@ololobus 👍 
@rndD странно, у меня
``` console
$ whois src2img.com | grep match
No match for domain "SRC2IMG.COM".
```

**Comment by ololobus** [comment]
@corpix @rndD Хз, где оно так удачно закэшировалось, но у меня в сафари без последнего слэша редиректит на src2img.com, а со слэшом все ок: https://team411.github.io/src2img/

В остальных браузерах и так и так норм. По-идее должно пройти со временем :)
Вот так пробовал чистить DNS-кэш `sudo killall -HUP mDNSResponder`, не помогло

**Comment by ololobus** [comment]
Таки будем считать, что с сабжем все-таки разобрались)

**Comment by ololobus** [comment]
Таки будем считать, что с сабжем все-таки разобрались)
