### ISSUE TITLE
Ace editor вместо textarea

### ISSUE THREAD

**Issue by rndD** [team411/src2img#2]

**Comment by rndD** [comment]
Прийдется убирать Highlight.js и будет меньше тем и меньше поддерживаемых языков.

**Comment by Andre-487** [comment]
А что, если не ставить Ace Editor, а реализовать самостоятельно фишку автоматических отступов? Тогда Highlight.js можно оставить на месте

**Comment by restrry** [comment]
Плюсую за последнее. самое простое решение, что видел http://jsfiddle.net/chim/53eAy/

**Comment by rndD** [comment]
Привет @Andre-487! Ты имеешь ввиду автоформат кода или то что предлагает @restrry?

**Comment by Andre-487** [comment]
Привет ) Я имел в виду базовый автоформат - то, чего не хватало лично мне. Автоматическое увеличение высоты поля - не уверен, что это нужно.

Увеличение размера шрифта можно тоже реализовать с обычной `textarea`.

Просто мне кажется, большой выбор тем куда важнее удобства разработки прямо в поле ввода. Там если и нужно что-то писать с нуля - что-то совсем простенькое, и для удобства не хватает только автоматических отступов.

**Comment by rndD** [comment]
Автоформат только для js? Там просто еще около 20 незнакомых мне языка =)

**Comment by Andre-487** [comment]
Мне кажется, для любого языка будет актуально следующее: Tab сдвигает каретку. Тут, конечно, есть проблема с отступами - не везде 4 пробела - корректный отступ, но можно изучить этот вопрос и задать отступ для языков индивидуально. Или забить и поставить везде отступ 2 пробела. Также при переносе строки, каретка сохраняет отступ, а не падает в начало строки. Лично я был бы счастлив, если бы было так. Могу даже прислат пулл-реквест, если ты не сделаешь раньше )

**Comment by rndD** [comment]
ok
