### ISSUE TITLE
Нет ссылки на gh в футере

### ISSUE THREAD

**Issue by rndD** [team411/src2img#4]

**Comment by corpix** [comment]
Где сохранить автора? Варианты:
  - github api, хранить в issue
  - Какая-нибудь http база
  - Свой бэкенд :)

**Comment by rndD** [comment]
Оу не, мне пожаловались что в футере нет ссылки на этот гитхаб проект.

**Comment by rndD** [comment]
В итоге сделал просто ленточку fork me. =)
