### ISSUE TITLE
Темы для кода не отсортированы

### ISSUE THREAD

**Issue by rndD** [team411/src2img#5]

**Comment by restrry** [comment]
нужно просто в лексикографический порядок?
https://github.com/team411/src2img/blob/master/common.blocks/select/_type/select_type_style.bemhtml#L54
```javascript
Object.keys(styles).map(function(style){  ===> Object.keys(styles).sort().map(function(style){
```
а можно просто вставить уже отсотированный, но вроде порядок обхода ключей не гарантируется
